[package]
name = "oxidase-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
httpdate.workspace = true
oxidase-core = { path = "../oxidase-core" }
oxidase-config = { path = "../oxidase-config" }
oxidase-runtime = { path = "../oxidase-runtime" }
oxidase-site = { path = "../oxidase-site" }
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true

[lints]
workspace = true
