[main]
DEBUG: false
SERVER_HOST: conformance.example.test
SERVER_IP: 127.0.0.1
SERVER_PORT: 18080
SERVER_SSL: false
SERVER_DEFAULT_LOCATION: /
SERVER_DEFAULT_LOCATION_CONTENT: It Works
CLIENT_SOCKET_READ_TIMEOUT_MS: 1500
BACKEND_PORT: 19080
BACKEND_LOCATION: /
I_HAVE_READ_AND_UNDERSTAND_THE_FAQ_AND_I_AM_RESPONSIBLE_OF_MY_ACTS: true
