[package]
name = "oxidase-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "oxidase"
path = "src/main.rs"

[features]
fuzzing = []

[dependencies]
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
oxidase-bundle = { path = "../oxidase-bundle" }
oxidase-config = { path = "../oxidase-config" }
oxidase-core = { path = "../oxidase-core" }
oxidase-runtime = { path = "../oxidase-runtime" }
oxidase-server = { path = "../oxidase-server" }
oxidase-site = { path = "../oxidase-site" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
zeroize.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
rustls-pki-types.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
