[package]
name = "oxidase-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "oxidase"
path = "src/main.rs"

[dependencies]
oxidase-config = { path = "../oxidase-config" }

[lints]
workspace = true

