[package]
name = "oxidase-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "oxidase"
path = "src/main.rs"

[dependencies]
bytes.workspace = true
clap.workspace = true
http.workspace = true
oxidase-config = { path = "../oxidase-config" }
oxidase-core = { path = "../oxidase-core" }
oxidase-runtime = { path = "../oxidase-runtime" }
oxidase-server = { path = "../oxidase-server" }
oxidase-site = { path = "../oxidase-site" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
