[package]
name = "oxidase-site"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
http.workspace = true
httpdate.workspace = true
mime_guess.workspace = true
oxidase-core = { path = "../oxidase-core" }
oxidase-source = { path = "../oxidase-source" }
percent-encoding.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
